// Code generated by `st pricing refresh`. DO NOT EDIT manually.
// To update rates: st pricing refresh (or --dry-run to preview)
// Source: https://docs.anthropic.com/en/docs/about-claude/pricing
package pricing

// table holds per-model USD rates per million tokens (MTok).
// Model IDs are canonical (e.g., "claude-opus-4-7"). Lookups normalize
// to lowercase; version suffixes like "-20260215" are tolerated.
var table = map[string]Rate{
	// Opus 4.x current generation
	"claude-opus-4-7": {Input: 5, Output: 25, CacheWrite5m: 6.25, CacheWrite1h: 10, CacheRead: 0.5},
	"claude-opus-4-6": {Input: 5, Output: 25, CacheWrite5m: 6.25, CacheWrite1h: 10, CacheRead: 0.5},
	"claude-opus-4-5": {Input: 5, Output: 25, CacheWrite5m: 6.25, CacheWrite1h: 10, CacheRead: 0.5},

	// Opus 4.0/4.1 (pre-price-drop — may not appear on current pricing page)
	"claude-opus-4-1": {Input: 15, Output: 75, CacheWrite5m: 18.75, CacheWrite1h: 30, CacheRead: 1.5},
	"claude-opus-4":   {Input: 15, Output: 75, CacheWrite5m: 18.75, CacheWrite1h: 30, CacheRead: 1.5},

	// Sonnet 4.x
	"claude-sonnet-4-6": {Input: 3, Output: 15, CacheWrite5m: 3.75, CacheWrite1h: 6, CacheRead: 0.3},
	"claude-sonnet-4-5": {Input: 3, Output: 15, CacheWrite5m: 3.75, CacheWrite1h: 6, CacheRead: 0.3},
	"claude-sonnet-4":   {Input: 3, Output: 15, CacheWrite5m: 3.75, CacheWrite1h: 6, CacheRead: 0.3},

	// Haiku
	"claude-haiku-4-5": {Input: 1, Output: 5, CacheWrite5m: 1.25, CacheWrite1h: 2, CacheRead: 0.1},
	"claude-haiku-3-5": {Input: 0.8, Output: 4, CacheWrite5m: 1, CacheWrite1h: 1.6, CacheRead: 0.08},
}
