package command

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// nonStateManagedPrefixes are the agent-state / machine-managed path prefixes
// that NonStateStash must leave alone. agent-state items are handled by
// OrphanStash; .as/.plans/agent-memory churn is regenerated. itemsPrefix
// (e.g. "agent-state/") is appended at runtime since it is configurable.
var nonStateManagedPrefixes = []string{".as/", ".plans/", "agent-memory/"}

// nonStateIsManaged reports whether path is an agent-state or machine-managed
// path that NonStateStash must NOT touch. itemsPrefix is the configured items
// root with a trailing slash (e.g. "agent-state/").
func nonStateIsManaged(path, itemsPrefix string) bool {
	if itemsPrefix != "" && strings.HasPrefix(path, itemsPrefix) {
		return true
	}
	for _, p := range nonStateManagedPrefixes {
		if strings.HasPrefix(path, p) {
			return true
		}
	}
	// Churn files regenerated by tooling — mirrors maintainIsChurn. Harmless
	// residue; never stash.
	base := filepath.Base(path)
	return base == "deploy-dashboard.html" || strings.HasSuffix(path, "dashboard-history.jsonl")
}

// NonStateStash parks uncommitted NON-state residue (scripts/, docs/, etc.)
// left in the SHARED theraprac-workspace main checkout by a peer, so it cannot
// silently block the next agent's state sync (I-1594). Two failure modes it
// clears: (A) staged non-state edits that trip checkNonStateGate and refuse
// `st sync`; (B) untracked non-state files that block the session-start
// `git pull --ff-only` ("untracked working tree files would be overwritten").
//
// Mirrors OrphanStash, with two deliberate differences:
//   - It is a STRICT NO-OP unless the checkout is on main/master. Feature-branch
//     worktrees carry the agent's own legitimate uncommitted non-state WIP; only
//     the shared main checkout should never hold non-state dirt. This branch
//     guard is the peer-WIP-protection boundary.
//   - It captures untracked files too (git stash push -u), because untracked
//     residue is failure-mode B.
//
// Nothing is deleted — every parked file is recoverable via `git stash` and the
// printed recovery line / `st orphan list`. Best-effort: any git error logs to
// stderr and processing continues; it never aborts startup.
func NonStateStash(workspaceRoot, itemsPrefix, agentID string) []string {
	// Branch guard: only the shared main checkout. symbolic-ref returns
	// refs/heads/<branch> on a branch, non-zero on detached HEAD.
	refOut, refErr := execGitOrphan(workspaceRoot, "symbolic-ref", "-q", "HEAD")
	if refErr != nil {
		return nil // detached HEAD or corrupt — fail safe, do nothing
	}
	branch := strings.TrimPrefix(strings.TrimSpace(string(refOut)), "refs/heads/")
	if branch != "main" && branch != "master" {
		return nil // feature branch — legitimate non-state WIP, leave it
	}

	// Normalize the items prefix to a trailing-slash form for HasPrefix.
	if itemsPrefix != "" && !strings.HasSuffix(itemsPrefix, "/") {
		itemsPrefix = itemsPrefix + "/"
	}

	// -z: NUL-terminated, raw bytes, no path quoting. Rename/copy entries
	// arrive as two NUL tokens: "<XY> <new>\0<old>\0".
	// --untracked-files=all: list individual untracked FILES, not collapsed
	// directories, so per-file churn/managed classification (and per-file
	// stashing) works for wholly-untracked dirs like docs/ or scripts/.
	out, err := execGitOrphan(workspaceRoot, "status", "--porcelain", "-z", "--untracked-files=all")
	if err != nil || len(out) == 0 {
		return nil
	}

	today := time.Now().UTC().Format("2006-01-02")
	var stashed []string
	seen := make(map[string]bool)

	tokens := strings.Split(string(out), "\x00")
	for i := 0; i < len(tokens); i++ {
		tok := tokens[i]
		if len(tok) < 4 {
			continue
		}
		code := tok[:2]
		path := tok[3:]
		// Rename/copy: the OLD path is the next token (no XY prefix). Stash
		// the NEW path (the residue that exists on disk now).
		if code[0] == 'R' || code[0] == 'C' {
			if i+1 < len(tokens) {
				i++ // consume the old-path token
			}
		}
		if path == "" || seen[path] {
			continue
		}
		// Leave agent-state, .as/.plans/agent-memory, and churn alone.
		if nonStateIsManaged(path, itemsPrefix) {
			continue
		}
		seen[path] = true

		label := fmt.Sprintf("st-nonstate-residue: %s dropped-by:%s date:%s",
			path, agentID, today)
		// -u captures the path even when it is untracked (failure-mode B);
		// harmless for tracked-modified paths.
		if _, stashErr := execGitOrphanCapture(workspaceRoot, "stash", "push", "-u",
			"-m", label, "--", path); stashErr != nil {
			fmt.Fprintf(os.Stderr, "nonstate-stash: failed to stash %s: %v\n", path, stashErr)
			continue
		}
		// git stash push prints a human message, not a ref — retrieve the real ref.
		ref := "stash@{?}"
		if refOut, err := execGitOrphan(workspaceRoot, "stash", "list",
			"--max-count=1", "--format=%gd"); err == nil {
			ref = strings.TrimSpace(string(refOut))
		}
		stashed = append(stashed, fmt.Sprintf("  %s → %s", path, ref))
	}

	if len(stashed) > 0 {
		fmt.Printf("nonstate-stash: parked %d non-state file(s) from the shared main checkout (dropped-by %s):\n", len(stashed), agentID)
		for _, s := range stashed {
			fmt.Println(s)
		}
		fmt.Printf("  these were peer residue blocking state sync; recover with: git -C %q stash apply <ref>\n", workspaceRoot)
		fmt.Printf("  list: st orphan list --workspace %q\n", workspaceRoot)
	}
	return stashed
}
